config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :playlists
  resources :songs, only: [:index]
  resources :artists, shallow: true do
    resources :songs, except: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  validates_presence_of :title, :length, :play_count
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    if Artist.create(artist_params)
      redirect_to '/artists'
    else
      redirect_to 'artists/new'
    end
  end

  def show
    require'pry';binding.pry
    @artist = Artist.find(params[:id])
    session[:secret] = "This time for real, though."
  end

  private

    def artist_params
      params.require(:artist).permit(:name)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
    @artist = Artist.find(params[:artist_id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    # song_data = song_params
    # song_data[:artist_id] = @artist.id
    # if Song.create(song_data)
    @song = @artist.songs.create(song_params)
    if @song.save
      redirect_to '/songs'
    else
      render :new
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :length, :play_count, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<header>
  <%= link_to "Add New Artist", new_artist_path %>
</header>

<% @artists.each do |artist| %>
  <p><%= link_to artist.name, artist_path(artist) %></p>
<% end %>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Unicase" rel="stylesheet">
    <title>MusicBox1804</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="/songs/index.css"/>
  <link href="https://fonts.googleapis.com/css?family=Knewave|Shadows+Into+Light" rel="stylesheet">
</head>
<body>
  <h1>All Songs</h1>

  <section class="songs">
    <% @songs.each do |song| %>
    <div class="one_song">
      <img src="/assets/Abbey_Road.jpg" alt="Album Cover from the Beatles Abbey Road" class='image'/>
      <div class='info'>
        <h2><%= song.title %></h2>
        <p><%= song.length %> seconds</p>
        <p>Plays: <%=song.play_count%></p>
      </div>
    </div>
    <%end%>
  </section>
</body>
</html>

app/views/songs/new.html.erb
<h2>Create A New Song</h2>


<%= form_for [@artist, @song], :id => "new-song-form" do |f| %>

  <div class="form-field">
    <p><%=f.label :title%></p>
    <%=f.text_field :title%>
  </div>

  <div class="form-field">
    <p><%=f.label :length%></p>
    <%=f.text_field :length%>
  </div>

  <div class="form-field">
    <p><%=f.label :play_count%></p>
    <%=f.text_field :play_count%>
  </div>

  <div class="form-field">
    <%=f.submit%>
  </div>
<%end%>